### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid int: "OS"

### ISSUE THREAD

**Issue by geeksville** [geeksville/arduleader#212]
``` bash
java.lang.IllegalArgumentException: Invalid int: "OS"
at android.os.Parcel.readException(Parcel.java:1624)
at android.os.Parcel.readException(Parcel.java:1573)
at android.speech.tts.ITextToSpeechService$Stub$Proxy.getVoices(ITextToSpeechService.java:796)
at android.speech.tts.TextToSpeech.getVoice(TextToSpeech.java:1769)
at android.speech.tts.TextToSpeech.access$1100(TextToSpeech.java:59)
at android.speech.tts.TextToSpeech$12.run(TextToSpeech.java:1581)
at android.speech.tts.TextToSpeech$12.run(TextToSpeech.java:1531)
at android.speech.tts.TextToSpeech$Connection.runAction(TextToSpeech.java:2337)
at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:747)
at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:737)
at android.speech.tts.TextToSpeech.setLanguage(TextToSpeech.java:1531)
at com.geeksville.aspeech.TTSClient$$anon$1.onInit(TTSClient.scala:32)
at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:820)
at android.speech.tts.TextToSpeech.access$1900(TextToSpeech.java:59)
at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2251)
at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2206)
at android.os.AsyncTask.finish(AsyncTask.java:651)
at android.os.AsyncTask.access$500(AsyncTask.java:180)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7224)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
java.lang.IllegalArgumentException: Invalid int: "OS"
at android.os.Parcel.readException(Parcel.java:1624)
at android.os.Parcel.readException(Parcel.java:1573)
at android.speech.tts.ITextToSpeechService$Stub$Proxy.getVoices(ITextToSpeechService.java:796)
at android.speech.tts.TextToSpeech.getVoice(TextToSpeech.java:1769)
at android.speech.tts.TextToSpeech.access$1100(TextToSpeech.java:59)
at android.speech.tts.TextToSpeech$12.run(TextToSpeech.java:1581)
at android.speech.tts.TextToSpeech$12.run(TextToSpeech.java:1531)
at android.speech.tts.TextToSpeech$Connection.runAction(TextToSpeech.java:2337)
at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:747)
at android.speech.tts.TextToSpeech.runAction(TextToSpeech.java:737)
at android.speech.tts.TextToSpeech.setLanguage(TextToSpeech.java:1531)
at com.geeksville.aspeech.TTSClient$$anon$1.onInit(TTSClient.scala:32)
at android.speech.tts.TextToSpeech.dispatchOnInit(TextToSpeech.java:820)
at android.speech.tts.TextToSpeech.access$1900(TextToSpeech.java:59)
at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2251)
at android.speech.tts.TextToSpeech$Connection$SetupConnectionAsyncTask.onPostExecute(TextToSpeech.java:2206)
at android.os.AsyncTask.finish(AsyncTask.java:651)
at android.os.AsyncTask.access$500(AsyncTask.java:180)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7224)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

```

**Comment by mvysny** [comment]
A bug in Samsung devices: http://developer.samsung.com/forum/board/thread/view.do?boardName=SDK&messageId=295016
and also http://stackoverflow.com/questions/26730082/illegalargumentexception-invalid-int-os-with-samsung-tts
